pub struct CicFlow {
    // BasicFlow
    pub basic_flow: BasicFlow,
    // General
    pub iat_mean: f64,
    pub iat_std: f64,
    pub iat_max: f64,
    pub iat_min: f64,
    // Forward
    pub fwd_pkt_len_tot: usize,
    pub fwd_pkt_len_max: usize,
    pub fwd_pkt_len_min: usize,
    pub fwd_pkt_len_mean: usize,
    pub fwd_pkt_len_std: usize,
    pub fwd_iat_total: f64,
    pub fwd_iat_mean: f64,
    pub fwd_iat_std: f64,
    pub fwd_iat_max: f64,
    pub fwd_iat_min: f64,
    pub fwd_header_length: usize,
    pub fwd_bulk_duration: f64,
    pub fwd_bulk_packet_count: u64,
    pub fwd_bulk_size_total: usize,
    pub fwd_bulk_state_count: u64,
    pub fwd_bulk_packet_count_help: u64,
    pub fwd_bulk_start_help: Instant,
    pub fwd_bulk_size_help: usize,
    pub fwd_last_bulk_timestamp: Instant,
    // Backward
    pub bwd_pkt_len_tot: usize,
    pub bwd_pkt_len_max: usize,
    pub bwd_pkt_len_min: usize,
    pub bwd_pkt_len_mean: usize,
    pub bwd_pkt_len_std: usize,
    pub bwd_iat_total: f64,
    pub bwd_iat_mean: f64,
    pub bwd_iat_std: f64,
    pub bwd_iat_max: f64,
    pub bwd_iat_min: f64,
    pub bwd_header_length: usize,
    pub bwd_bulk_duration: f64,
    pub bwd_bulk_packet_count: u64,
    pub bwd_bulk_size_total: usize,
    pub bwd_bulk_state_count: u64,
    pub bwd_bulk_packet_count_help: u64,
    pub bwd_bulk_start_help: Instant,
    pub bwd_bulk_size_help: usize,
    pub bwd_last_bulk_timestamp: Instant,
}

impl CicFlow {
    fn new(ipv4_source: u32, port_source: u16, ipv4_destination: u32, port_destination: u16, protocol: u8) -> Self {
        let cic_flow = CicFlow {
            basic_flow: BasicFlow::new(ipv4_source, port_source, ipv4_destination, port_destination, protocol),
            fwd_pkt_len_tot: 0,
            bwd_pkt_len_tot: 0,
            fwd_pkt_len_max: 0,
            fwd_pkt_len_min: 0,
            fwd_pkt_len_mean: 0,
            fwd_pkt_len_std: 0,
            bwd_pkt_len_max: 0,
            bwd_pkt_len_min: 0,
            bwd_pkt_len_mean: 0,
            bwd_pkt_len_std: 0,
            iat_mean: 0.0,
            iat_std: 0.0,
            iat_max: 0.0,
            iat_min: 0.0,
            fwd_iat_total: 0.0,
            fwd_iat_mean: 0.0,
            fwd_iat_std: 0.0,
            fwd_iat_max: 0.0,
            fwd_iat_min: 0.0,
            bwd_iat_total: 0.0,
            bwd_iat_mean: 0.0,
            bwd_iat_std: 0.0,
            bwd_iat_max: 0.0,
            bwd_iat_min: 0.0,
            fwd_header_length: 0,
            bwd_header_length: 0,
            fwd_bulk_duration: 0.0,
            fwd_bulk_packet_count: 0,
            fwd_bulk_size_total: 0,
            fwd_bulk_state_count: 0,
            fwd_bulk_packet_count_help: 0,
            fwd_bulk_start_help: Instant::now(),
            fwd_bulk_size_help: 0,
            fwd_last_bulk_timestamp: Instant::now(),
            bwd_bulk_duration: 0.0,
            bwd_bulk_packet_count: 0,
            bwd_bulk_size_total: 0,
            bwd_bulk_state_count: 0,
            bwd_bulk_packet_count_help: 0,
            bwd_bulk_start_help: Instant::now(),
            bwd_bulk_size_help: 0,
            bwd_last_bulk_timestamp: Instant::now(),
        };
    }
}