name: Rust Aya eBPF CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        components: rust-src, llvm-tools-preview
        override: true
    
    - name: Install bpf-linker
      run: cargo install bpf-linker

    - name: Build ingress eBPF program ipv4
      run: cargo xtask ingress-ebpf-ipv4

    - name: Build egress eBPF program ipv4
      run: cargo xtask egress-ebpf-ipv4
    
    - name: Build ingress eBPF program ipv6
      run: cargo xtask ingress-ebpf-ipv6

    - name: Build egress eBPF program ipv6
      run: cargo xtask egress-ebpf-ipv6

    - name: Build userspace program
      run: cargo build --verbose

    - name: Fetch gh-pages branch
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: git fetch origin gh-pages:gh-pages

    - name: Backup custom index.html
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        git checkout gh-pages
        mv index.html index.html.backup
        git checkout -
      
    - name: Run tests
      run: cargo test --verbose
      
    - name: Generate documentation
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: cargo doc --no-deps

    - name: Restore custom index.html
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: mv index.html.backup target/doc/index.html

    - name: Push docs to gh-pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc
        publish_branch: gh-pages
