name: Rust Aya eBPF CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        components: rust-src, llvm-tools-preview
        override: true
    
    - name: Install bpf-linker
      run: cargo install bpf-linker

    - name: Build ingress eBPF program
      run: cargo xtask ingress-ebpf

    - name: Build egress eBPF program
      run: cargo xtask egress-ebpf

    - name: Build userspace program
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose
      
    - name: Generate documenation
      run: cargo doc --no-deps
